<?php

namespace AppBundle\Repository;

/**
 * NotepadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotepadRepository extends \Doctrine\ORM\EntityRepository
{
}
